### PR TITLE
improvements for array_indexof for missing elements

### PR DESCRIPTION
**Pull request by aclemons**
Fixes makefu#7

Now you can use array_indexof to check for existence in a script with  'set -e' without jumping through hoops.

### CODE REVIEW

**Comment by aclemons** [comment]
I tried this but then backslash escapes are interpreted. The test:

    idx=$(echo "$A" | array_indexof "/\#$^")

then failed. But maybe there is some foo to escape the variable to avoid this in awk.

**Comment by 4z3** [comment]
Thanks for the heads-up, wasn't aware of that behavior.

**Comment by 4z3** [comment]
LGTM

**Comment by makefu** [comment]
@aclemons  thanks!

**Pull request merged**
